# Generated by Django 5.2 on 2025-05-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_petrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_petrol.car')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_petrol.person')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_petrol.station')),
            ],
            options={
                'verbose_name': 'Маршрут',
            },
        ),
    ]
